### PR TITLE
Build for ogre 1.10 and 1.12

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Review by traversaro — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
I think this is good to go as soon as quay is back up. @wolfv do you want to have a look whether the pinnings look fine?

**Comment by Tobias-Fischer** [comment]
@traversaro what's the idea to deal with downstream packages (libignition-gui4 and libignition-sensors4)? Do a similar treatment and build them with two variants?

For context, [this PR](https://github.com/conda-forge/libignition-sensors-feedstock/pull/3) caused the PR here.

**Comment by traversaro** [comment]
> @traversaro what's the idea to deal with downstream packages (libignition-gui4 and libignition-sensors4)? Do a similar treatment and build them with two variants?

I think that as long

**Comment by traversaro** [comment]
> > @traversaro what's the idea to deal with downstream packages (libignition-gui4 and libignition-sensors4)? Do a similar treatment and build them with two variants?
> 
> I need to check ignition-rendering, but if the OGRE headers are not included as part of the public headers of ignition-rendering, probably there is no reason to have two builds of downstream libraries?

I checked, and while ignition-rendering installs some headers with ogre neither ignition-gui nor ignition-sensors use them, so in theory the build should work fine with both ogre 1.10 and 1.12 . For downstream libraries such as ignition-sensors that seems to have runtime problems with ogre 1.12, what I was thinking to do is to have a run_constrained requirement  ( https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run-constrained ) on ogre.

**Comment by traversaro** [comment]
> I checked, and while ignition-rendering installs some headers with ogre neither ignition-gui nor ignition-sensors use them, so in theory the build should work fine with both ogre 1.10 and 1.12 .

However, this is just a theory, and we could have subtle problems related to this, so a safer alternative could be to just depend explicitly on ogre and build the two variants for all downstream libraries (this would have the advantage that we explicitly run the test suite against both ogre 1.12 and 1.10 and we easily detect problems).

**Comment by traversaro** [comment]
In any case, I think this PR is good to go.

**Comment by Tobias-Fischer** [comment]
Agreed - shall we merge @wolfv?

**Pull request merged**
